# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: halal-screen-proto/converter_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*halal-screen-proto/converter_service.proto\"]\n\x0e\x43onvertRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.ConvertContentType\x12\x17\n\x0f\x62lur_percentage\x18\x03 \x01(\r\"\"\n\x0f\x43onvertResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c**\n\x12\x43onvertContentType\x12\t\n\x05IMAGE\x10\x00\x12\t\n\x05VIDEO\x10\x01\x32@\n\x10\x43onverterService\x12,\n\x07\x43onvert\x12\x0f.ConvertRequest\x1a\x10.ConvertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'halal_screen_proto.converter_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONVERTCONTENTTYPE']._serialized_start=177
  _globals['_CONVERTCONTENTTYPE']._serialized_end=219
  _globals['_CONVERTREQUEST']._serialized_start=46
  _globals['_CONVERTREQUEST']._serialized_end=139
  _globals['_CONVERTRESPONSE']._serialized_start=141
  _globals['_CONVERTRESPONSE']._serialized_end=175
  _globals['_CONVERTERSERVICE']._serialized_start=221
  _globals['_CONVERTERSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
